Lecture/PreferMap:
  Description: '`each` can be replaced with `map`'
  Enabled: true
  VersionAdded: '0.1.3'

Lecture/ReplaceElsif:
  Description: "`elsif` can be replaced with `case`"
  Enabled: true
  VersionAdded: "0.1.0"

Lecture/UnlessElse:
  Description: "Do not use `unless` with `else`. Rewrite these with the positive case first."
  Enabled: true
  VersionAdded: "0.1.3"
